{% set version = "0.0.8" %}

package:
  name: xlum
  version: {{ version }}


requirements:
  build:
    - python={{ python_version }}
  run:
    - python={{ python_version }}

  
source:
  path: .

build:
  script: python -m build
        --sdist
        --wheel
        --outdir dist/
        .

about:
  home: https://github.com/SteveGrehl/xlum-python
  license: MIT
  description: |
    This module analyzes jpeg/jpeg2000/png/gif image header and
    return image size.
  dev_url: https://github.com/SteveGrehl/xlum-python
  doc_url: https://github.com/SteveGrehl/xlum-python/blob/main/docs/GITHUB.md
  doc_source_url: https://github.com/SteveGrehl/xlum-python/tree/main/src/xlum
  summary: "python importer for the XLUM data exchange and archive format"
