name: xlum tests

on:
  push:
    branches:
      - main
      - "feat/**"
  pull_request:
    branches: ["main"]

# see: https://docs.astral.sh/uv/guides/integration/github/#multiple-python-versions
jobs:
  build:
    name: continuous-integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install xlum python package
        run: uv sync --locked

      - name: Install pytest (not part of package dependencies)
        run: uv pip install pytest

      - name: Run tests
        run: uv run pytest tests
